[Variables]
fontface=Share Tech Mono
ProcessInterval=5
lightColor1=156,172,161,255
lightColor2=156,172,161,150
darkColor1=51,67,58,255
darkColor2=30,30,30,255
darkColor3=51,67,58,100
whiteColor=255,255,255,255
Scanlines=         

;Menu Items

Item1Text=Firefox
Item1Target=C:\Program Files (x86)\Mozilla Firefox\firefox.exe
Item1Desc=Internet web browser
Item2Text=Documents
Item2Target=E:\Fahd\Documents
Item2Desc=User documents
Item3Text=Photos
Item3Target=E:\Fahd\Photos
Item3Desc=User pictures and photographs
Item4Text=Music
Item4Target=E:\Fahd\Music
Item4Desc=User music collection
Item5Text=Videos
Item5Target=E:\Fahd\Videos
Item5Desc=User video collection
Item6Text=Dropbox
Item6Target=E:\Fahd\Dropbox
Item6Desc=Dropbox syncing folder
Item7Text=Downloads
Item7Target=C:\Users\Fahd\Downloads
Item7Desc=Common internet downloads folder
Item8Text=Trash
Item8Target=shell:RecycleBinFolder
Item8Desc=Recycle bin
Item9Text=Apps
Item9Target=E:\Fahd\Resources\Apps
Item9Desc=Commonly used applications
Item10Text=Games
Item10Target=E:\Fahd\Resources\Games
Item10Desc=Installed games
